#ifndef CS_ENUMS_CGINC
#define CS_ENUMS_CGINC

#define PROJECTION_FLAT 0
#define PROJECTION_SPHERE 1
#define PROJECTION_MESH 2
#define PROJECTION_WALLS 3
#define PROJECTION_TRIPLANAR 4

#define BLENDMODE_MULTIPLY 0
#define BLENDMODE_SCREEN 1
#define BLENDMODE_OVERLAY 2
#define BLENDMODE_ADD 3
#define BLENDMODE_SUBTRACT 4
#define BLENDMODE_DIFFERENCE 5
#define BLENDMODE_DIVIDE 6
#define BLENDMODE_DARKEN 7
#define BLENDMODE_LIGHTEN 8
#define BLENDMODE_NORMAL 9
#define BLENDMODE_COLORDODGE 10
#define BLENDMODE_COLORBURN 11
#define BLENDMODE_HARDLIGHT 12
#define BLENDMODE_SOFTLIGHT 13
#define BLENDMODE_EXCLUSION 14

#define BOUNDARYMODE_CLAMP 0
#define BOUNDARYMODE_REPEAT 1
#define BOUNDARYMODE_OVERLAY 2
#define BOUNDARYMODE_SCREEN 2

#define OVERLAY_IMAGE 0
#define OVERLAY_FLIPBOOK 1
#define OVERLAY_CUBEMAP 2

#define DISTORT_NORMAL 0
#define DISTORT_MELT 1

#define DISTORT_TARGET_SCREEN 0
#define DISTORT_TARGET_OVERLAY 1
#define DISTORT_TARGET_BOTH 2

#define FALLOFF_CURVE_SHARP 0
#define FALLOFF_CURVE_LINEAR 1
#define FALLOFF_CURVE_SMOOTH 2

#define MIRROR_NORMAL 0
#define MIRROR_DISABLE 1
#define MIRROR_ONLY 2

#define EYE_BOTH 0
#define EYE_LEFT 1
#define EYE_RIGHT 2

#define PLATFORM_ALL 0
#define PLATFORM_DESKTOP 1
#define PLATFORM_VR 2

#endif
